# Generated by Django 5.2 on 2025-05-12 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Вход')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Выход')),
                ('break_minutes', models.PositiveIntegerField(default=0, verbose_name='Перерыв (мин)')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись рабочего времени',
                'verbose_name_plural': 'Рабочие записи',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
