# Generated by Django 5.2 on 2025-04-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_site', '0002_customuser_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='descripion',
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
