# Generated by Django 5.2 on 2025-05-14 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_site', '0003_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start', models.TimeField(verbose_name='Начало работы')),
                ('work_end', models.TimeField(verbose_name='Конец работы')),
                ('working_days', models.CharField(default='1,2,3,4,5', help_text='Дни недели: 0=Вс, 1=Пн, ..., 6=Сб. Через запятую', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
    ]
