# Generated by Django 5.2 on 2025-04-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_site', '0003_remove_customuser_descripion_customuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.CharField(blank=True, max_length=100, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='employee', max_length=50, verbose_name='role'),
        ),
    ]
