# Generated by Django 5.2 on 2025-05-15 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_site', '0004_workschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start', models.TimeField()),
                ('work_end', models.TimeField()),
                ('working_days', models.CharField(default='0,1,2,3,4', help_text='Дни недели, когда работает отдел: 0=Пн, ..., 6=Вс', max_length=20)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='time_site.department')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
    ]
