# Generated by Django 5.2 on 2025-04-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_site', '0004_alter_customuser_post_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Сотрудник', 'Сотрудник'), ('Руководитель', 'Руководитель'), ('Администратор', 'Администратор')], default='Сотрудник', max_length=50, verbose_name='role'),
        ),
    ]
