# Generated by Django 5.2 on 2025-05-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_site', '0005_departmentworkschedule_delete_workschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentworkschedule',
            name='working_days',
            field=models.CharField(max_length=20),
        ),
    ]
