# Generated by Django 5.2 on 2025-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_site', '0006_alter_departmentworkschedule_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('отпуск', 'Отпуск'), ('отгул', 'Отгул'), ('командировка', 'Командировка'), ('больничный', 'Больничный'), ('удалёнка', 'Удалёнка')], max_length=20),
        ),
    ]
