# Generated by Django 5.2 on 2025-05-17 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_site', '0007_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('due_date', models.DateField(verbose_name='Срок сдачи')),
                ('status', models.CharField(choices=[('свободна', 'Свободна'), ('в работе', 'В работе'), ('завершена', 'Завершена')], default='свободна', max_length=20, verbose_name='Статус')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_site.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Задача команды',
                'verbose_name_plural': 'Задачи команды',
                'ordering': ['due_date'],
            },
        ),
    ]
